# Generated by Django 4.2.1 on 2023-05-23 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blindcatb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetail',
            name='product',
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blindcatb.Product'),
        ),
        migrations.AddField(
            model_name='buy',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buy',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
