# Generated by Django 4.2.1 on 2023-05-23 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blindcatb', '0002_remove_purchasedetail_product_buy_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blindcatb.product'),
        ),
    ]
